export const CHANGEUSR = 'changeUser'
export const GETAREAS = 'getAreas'
export const GETLIVEDATALIST = 'getLiveDataList'
export const GETMENULIST = 'getMenuList'
export const GETROLELIST = 'getRoleList'
export const GETWELLLIST = 'getWellList'
export const GETWATERAREAS = 'getWaterAreas'
